baseURL = "/"
theme = "terminal"
publishDir = "docs"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableLanguages = []
linkedin = "https://www.linkedin.com/in/vinicius-manuel-martins-5010a7186/"
github = "https://github.com/Vanfarock"

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    languageCode = "en-us"
    weight = 1
  [languages.pt]
    languageName = "Português"
    contentDir = "content/pt"
    languageCode = "pt-br"
    weight = 2

[params]
math = "mathjax"
contentTypeName = "posts"
showMenuItems = 3
showLanguageSelector = true
fullWidthTheme = false
centerTheme = true
autoCover = true
showLastUpdated = false
updatedDatePrefix = "Updated"
readingTime = false
Toc = false
TocTitle = "Table of Contents"
dateFormat = "2006-01-02"

[[redirects]]
from = "/"
to = "/pt/"
status = 302

[[redirects]]
from = "/about/"
to = "/pt/about/"
status = 302

[[redirects]]
from = "/posts/"
to = "/pt/posts/"
status = 302
